import { IProduct } from './products';
import { IVisitas } from './visitas';
// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numeroOrdenes      :number;
    ordenesPendientes  :number;
    ordenesEnProceso   :number;
    ordenesFinalizadas :number;
    clientes           :number;
    productos          :number;
    categorias         :number;
    marcas             :number;
    numeroVisitas      :IVisitas[];
    productosMarcas    :IProduct[];
}